version: '3.8'
services:
  db:
    build: .
    container_name: docker-mysql-catalog
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 230461
      MYSQL_DATABASE: catalog_database
      MYSQL_USER: user
      MYSQL_PASSWORD: 413191
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
